"""
Vivado Feedback Timer - maps FEM placement back to Vivado for exact timing.
"""

import os
import torch
from typing import Dict, List, Optional, Any
from .logger import INFO, WARNING, ERROR
from .timer import TimingSummary, TimingAnalyzer

# Legacy alias kept for backward compatibility
def generate_vivado_timing_tcl(*args, **kwargs):
    from .logger import WARNING
    WARNING("generate_vivado_timing_tcl() is deprecated. "
            "Use VivadoTimingRunner.run() instead.")
    runner = VivadoTimingRunner()
    return runner.run(*args, **kwargs)


class VivadoTimingRunner:
    """
    Maps FEM placement to Vivado for routing and timing analysis.

    FLOW:
      1. Map FEM grid coords to physical sites and emit ``set_property LOC``
         constraints (one per primitive cell).
      2. Write the original DCP (unmodified).
      3. Generate a Vivado Tcl that sets these LOC constraints, runs
         ``place_design`` + ``route_design``, and reports timing.
    """

    def __init__(
        self,
        vivado_path: str = 'vivado',
        work_dir: str = './vivado/fem_timing',
    ):
        self.vivado_path = vivado_path
        self.work_dir = work_dir

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def run(
        self,
        design: Any,
        placer: Any,
        logic_coords: torch.Tensor,
        io_coords: Optional[torch.Tensor] = None,
        include_io: bool = False,
        clock_period_ns: float = 5.0,
        output_dir: Optional[str] = None,
        instance_name: str = 'fem_placement',
        run_vivado: bool = True,
        keep_files: bool = True,
    ) -> TimingSummary:
        import time as _time

        if output_dir is None:
            output_dir = os.path.join(self.work_dir, instance_name)
        os.makedirs(output_dir, exist_ok=True)

        placed_dcp = os.path.abspath(
            os.path.join(output_dir, 'fem_placed.dcp')).replace('\\', '/')
        tcl_path = os.path.abspath(
            os.path.join(output_dir, 'place_and_route.tcl')).replace('\\', '/')
        impl_dcp = os.path.abspath(
            os.path.join(output_dir, 'post_route.dcp')).replace('\\', '/')
        timing_rpt = os.path.abspath(
            os.path.join(output_dir, 'timing_summary.rpt')).replace('\\', '/')
        metrics_txt = os.path.abspath(
            os.path.join(output_dir, 'timing_metrics.txt')).replace('\\', '/')

        # --- Step 1: Place FEM sites via RapidWright API (moves entire
        #     SiteInsts, preserving all BEL relationships) ---
        t0 = _time.time()
        from fem_placer.rapidwright_timer import RapidWrightTimer
        rwt = RapidWrightTimer()
        rwt._place_fem_sites(design, placer, logic_coords, io_coords, include_io)
        rwt._replace_clock_buffers(design, placer)
        INFO(f"[VivadoTimingRunner] FEM placement applied via RapidWright "
             f"({_time.time()-t0:.1f}s)")

        # --- Step 2: Write placed DCP ---
        t0 = _time.time()
        design.writeCheckpoint(placed_dcp)
        INFO(f"[VivadoTimingRunner] Placed DCP written to {placed_dcp} "
             f"({_time.time()-t0:.1f}s)")

        # --- Step 3: Generate Tcl (route + timing only; placement is
        #     already baked into the DCP) ---
        self._write_tcl(tcl_path, placed_dcp, impl_dcp, timing_rpt,
                        metrics_txt, clock_period_ns)

        # --- Step 4: Run Vivado ---
        if run_vivado:
            t0 = _time.time()
            retcode = self._run_vivado(tcl_path, output_dir)
            INFO(f"[VivadoTimingRunner] Vivado finished (ret={retcode}) "
                 f"in {_time.time()-t0:.1f}s")

        # --- Step 5: Parse results ---
        result = self._parse_results(metrics_txt, timing_rpt, clock_period_ns)

        if not keep_files:
            for p in [tcl_path, placed_dcp]:
                if os.path.exists(p):
                    os.remove(p)
        return result

    # ------------------------------------------------------------------
    # Write Tcl
    # ------------------------------------------------------------------

    def _write_tcl(
        self,
        tcl_path: str,
        placed_dcp: str, impl_dcp: str,
        timing_rpt: str, metrics_txt: str,
        clock_period_ns: float,
        loc_commands: Optional[List[str]] = None,
    ):
        loc_str = '\n'.join(loc_commands) if loc_commands else ''
        clock_port = 'clk'

        tcl = f"""# Auto-generated by VivadoTimingRunner

puts "========================================"
puts "FEM Placement Feedback - Route & Time"
puts "========================================"

# Open DCP (RapidWright-modified DCPs may trigger an integrity
# warning, but the design data is valid)
puts "Opening checkpoint: {placed_dcp}"
open_checkpoint {placed_dcp}

# --- Legalise BELs ---
# The DCP already has site-level placement via RapidWright's
# site_inst.place().  Vivado adjusts BEL assignments for the new sites.
puts "Legalising BEL-level placement ..."
place_design -directive Quick

# --- Route ---
puts "Routing ..."
route_design

# --- Save routed checkpoint ---
write_checkpoint -force {impl_dcp}

# --- Create clock and report timing ---
puts "Creating clock with period {clock_period_ns} ns on port {clock_port}"
create_clock -period {clock_period_ns} -name sys_clk [get_ports {clock_port}]

puts "Reporting timing ..."
report_timing_summary -file {timing_rpt} -delay_type min_max
report_timing -max_paths 10 -nworst 10 \\
    -file [file join [file dirname {timing_rpt}] critical_paths.rpt] -setup
report_route_status \\
    -file [file join [file dirname {timing_rpt}] route_status.rpt]

# --- Extract WNS / TNS ---
set paths [get_timing_paths -max_paths 1 -nworst 1 -setup]
if {{ [llength $paths] > 0 }} {{
    set wns [get_property SLACK [lindex $paths 0]]
    puts "WNS: $wns ns"
}} else {{
    set wns "N/A"
}}

set tns 0.0
foreach path [get_timing_paths -max_paths 1000 -nworst 1000 -setup] {{
    set slack [get_property SLACK $path]
    if {{ $slack < 0 }} {{
        set tns [expr {{$tns + $slack}}]
    }}
}}
puts "TNS: $tns ns"

set fp [open {metrics_txt} w]
puts $fp "WNS: $wns"
puts $fp "TNS: $tns"
if {{ $wns != "N/A" }} {{
    set period {clock_period_ns}
    set fmax [expr {{1000.0 / ($period - $wns)}}]
    puts $fp "Fmax (MHz): $fmax"
}}
close $fp

puts "Done. Results in [file dirname {timing_rpt}]"
quit
"""
        with open(tcl_path, 'w') as f:
            f.write(tcl)

    # ------------------------------------------------------------------
    # Run Vivado
    # ------------------------------------------------------------------

    def _run_vivado(self, tcl_path: str, output_dir: str) -> int:
        import subprocess
        cmd = [self.vivado_path, '-mode', 'batch', '-source', tcl_path]
        INFO(f"[VivadoTimingRunner] Running: {' '.join(cmd)}")
        result = subprocess.run(cmd, capture_output=True, text=True,
                                shell=True, timeout=3600)
        log_path = os.path.abspath(
            os.path.join(output_dir, 'vivado_feedback.log')).replace('\\', '/')
        with open(log_path, 'w') as f:
            f.write(result.stdout)
            f.write('\n--- STDERR ---\n')
            f.write(result.stderr)
        if result.returncode != 0:
            WARNING(f"[VivadoTimingRunner] Vivado returned {result.returncode}. "
                    f"See {log_path} for details.")
        return result.returncode

    # ------------------------------------------------------------------
    # Parse results
    # ------------------------------------------------------------------

    def _parse_results(
        self, metrics_txt: str, timing_rpt: str, clock_period_ns: float,
    ) -> TimingSummary:
        wns = 'N/A'
        tns = 'N/A'
        fmax = 'N/A'
        if os.path.exists(metrics_txt):
            try:
                with open(metrics_txt, 'r') as f:
                    for line in f:
                        if ':' in line:
                            k, v = line.split(':', 1)
                            k, v = k.strip(), v.strip()
                            if k == 'WNS':
                                wns = v
                            elif k == 'TNS':
                                tns = v
                            elif 'Fmax' in k or 'fmax' in k:
                                fmax = v
            except Exception:
                pass

        if wns == 'N/A' and os.path.exists(timing_rpt):
            analyzer = TimingAnalyzer()
            ts = analyzer.parse_vivado_report(timing_rpt)
            if ts is not None:
                wns = f"{ts.wns*1e9:.3f}"
                tns = f"{ts.tns*1e9:.3f}"

        def _sf(s, default=0.0):
            try:
                return float(s)
            except (ValueError, TypeError):
                return default

        wns_f, tns_f, fmax_f = _sf(wns), _sf(tns), _sf(fmax)
        if fmax_f <= 0 and wns_f != 0:
            est_p = max(clock_period_ns - wns_f, 0.01)
            fmax_f = 1000.0 / est_p

        est_period = clock_period_ns - wns_f if wns_f != 0 else clock_period_ns
        return TimingSummary(
            wns=wns_f * 1e-9,
            tns=tns_f * 1e-9,
            fmax=fmax_f * 1e6,
            estimated_period=est_period * 1e-9,
            critical_path_delay=est_period * 1e-9,
            logic_depth=0,
            num_paths=0,
            num_violations=0,
        )
