"""
Analyze FPGA placement file and compute HPWL (Half-Perimeter Wire Length).

HPWL is computed at the **site level** (grid x, y coordinates), NOT at the BEL
(sub-block) level. This matches the approach used in the FEM placer framework
(see test_fpga_placement.py) — only the site position matters for wire length,
not which specific BEL within a site a block occupies.

Supports two input formats:

1. VPR .place format (--format vpr, default for .place files):
       Placement generated by VPR (version x.x)
       Netlist file: <name>.net  Architecture file: <arch>
       Array size: <nx> x <ny> logic blocks
       #block name	x	y	subblk	block_number
       <block_name>  <x>  <y>  <subblk>  #<block_number>

   Only (x, y) site-level coordinates are used; subblk (BEL) is ignored.

2. Bookshelf .pl format (--format bookshelf, default for .pl files):
       <instance_name> <x> <y> <bel> [FIXED]

   Only (x, y) site-level coordinates are used; bel is ignored.

Usage:
    python scripts/analyze_vpr_place.py <circuit_name> [--place_dir <dir>]
    python scripts/analyze_vpr_place.py <circuit_name> --format bookshelf
    
    # VPR format (default)
    python scripts/analyze_vpr_place.py c2670 --place_dir ./results

    # ISPD Bookshelf format
    python scripts/analyze_vpr_place.py FPGA-example1 --format bookshelf --place_dir ./benchmarks/ISPD/FPGA-example1
"""

import argparse
import os
import re
from collections import defaultdict


def detect_format(place_path: str) -> str:
    """Auto-detect whether the file is VPR .place or Bookshelf .pl format."""
    ext = os.path.splitext(place_path)[1].lower()
    if ext == '.pl':
        return 'bookshelf'
    # Check the first few lines
    with open(place_path, 'r') as f:
        first_lines = [next(f).strip() for _ in range(5) if f]
    # VPR format has header lines starting with keywords
    for line in first_lines:
        if line.startswith('Placement') or line.startswith('Netlist') or \
           line.startswith('Array') or line.startswith('#block'):
            return 'vpr'
    # Bookshelf format has no headers, first line is data
    return 'bookshelf'


def parse_place_file_vpr(place_path: str) -> dict:
    """
    Parse a VPR .place file and return a dict mapping block_name -> (x, y).

    Only site-level (x, y) coordinates are extracted; the subblk (BEL) field
    is ignored. This matches the site-level HPWL convention used in the
    FEM placer framework (test_fpga_placement.py).

    VPR .place format:
        #block name  x  y  subblk  #block_number
        <block_name> <x> <y> <subblk> #<block_number>

    Args:
        place_path: Path to the .place file.

    Returns:
        dict: {block_name: (x_coord, y_coord)}  — site-level only
    """
    coords = {}
    with open(place_path, 'r') as f:
        for line in f:
            line = line.strip()
            # Skip header lines
            if not line or line.startswith('Placement') or \
               line.startswith('Netlist') or line.startswith('Array') or \
               line.startswith('#'):
                continue
            # Parse data line: block_name  x  y  subblk  #block_number
            # We take only fields [0]=name, [1]=x, [2]=y (site-level).
            # Fields [3]=subblk (BEL), [4]=block_number are ignored.
            parts = line.split()
            if len(parts) >= 5:
                block_name = parts[0]
                x = int(parts[1])
                y = int(parts[2])
                coords[block_name] = (x, y)
    return coords


def parse_place_file_bookshelf(pl_path: str) -> dict:
    """
    Parse a Bookshelf-format .pl file and return a dict mapping
    instance_name -> (x, y).

    Only site-level (x, y) coordinates are extracted; the BEL field is
    ignored. This matches the Bookshelf placement file format used by
    ISPD FPGA benchmarks (see benchmarks/ISPD/).

    Bookshelf .pl format:
        <instance_name> <x> <y> <bel> [FIXED]

    Args:
        pl_path: Path to the .pl file.

    Returns:
        dict: {instance_name: (x_coord, y_coord)}  — site-level only
    """
    coords = {}
    with open(pl_path, 'r') as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            # Skip header lines (if any)
            if line.startswith('#'):
                continue
            # Parse: inst_name  x  y  bel  [status]
            # We take only fields [0]=name, [1]=x, [2]=y (site-level).
            # Field [3]=bel (BEL within site) is ignored.
            parts = line.split()
            if len(parts) >= 4:
                inst_name = parts[0]
                x = int(parts[1])
                y = int(parts[2])
                coords[inst_name] = (x, y)
    return coords


def parse_net_file_bookshelf(net_path: str) -> dict:
    """
    Parse a Bookshelf-format .nets file.

    Bookshelf .nets format:
        net <net_name> <degree>
            <instance_name> <pin_type>
        endnet

    Returns:
        dict: {net_name: [instance_name1, instance_name2, ...]}
    """
    nets = {}
    with open(net_path, 'r') as f:
        content = f.read()

    pattern = re.compile(
        r'net\s+(\S+)\s+\d+\s*\n(.*?)\nendnet',
        re.DOTALL | re.IGNORECASE
    )
    matches = pattern.findall(content)
    for net_name, body in matches:
        blocks = []
        for line in body.strip().split('\n'):
            line = line.strip()
            if line:
                parts = line.split()
                if parts:
                    blocks.append(parts[0])
        if len(blocks) >= 2:
            nets[net_name] = blocks
    return nets


def parse_net_file_vpr(net_path: str) -> dict:
    """
    Parse a VPR .net file.

    VPR .net format:
        Net <idx>: <net_name>
        <block_name>  <pin_type>
        ...
        endnet

    Returns:
        dict: {net_name: [block_name1, block_name2, ...]}
    """
    nets = {}
    current_net = None
    current_blocks = []

    with open(net_path, 'r') as f:
        for line in f:
            line = line.strip()
            if not line:
                continue

            net_header_match = re.match(r'Net\s+\d+:\s+(.+)', line)
            if net_header_match:
                if current_net is not None and len(current_blocks) >= 2:
                    nets[current_net] = current_blocks
                current_net = net_header_match.group(1).strip()
                current_blocks = []
                continue

            if line.lower() == 'endnet':
                if current_net is not None and len(current_blocks) >= 2:
                    nets[current_net] = current_blocks
                current_net = None
                current_blocks = []
                continue

            if current_net is not None:
                parts = line.split()
                if len(parts) >= 1:
                    block_name = parts[0]
                    if block_name != current_net:
                        current_blocks.append(block_name)

    if current_net is not None and len(current_blocks) >= 2:
        nets[current_net] = current_blocks

    return nets


def parse_netlist(net_path: str, fmt: str = 'auto') -> dict:
    """
    Parse a netlist file, auto-detecting VPR or Bookshelf format.

    Args:
        net_path: Path to the .net file.
        fmt: 'vpr', 'bookshelf', or 'auto'.

    Returns:
        dict: {net_name: [block_name1, block_name2, ...]}
    """
    if fmt == 'bookshelf':
        return parse_net_file_bookshelf(net_path)
    if fmt == 'vpr':
        return parse_net_file_vpr(net_path)

    # Auto-detect: try Bookshelf first, fall back to VPR
    nets = parse_net_file_bookshelf(net_path)
    if nets:
        return nets
    return parse_net_file_vpr(net_path)


def compute_hpwl(coords: dict, nets: dict) -> dict:
    """
    Compute HPWL for each net and total HPWL using **site-level** coordinates.

    HPWL for a net = (max_x - min_x) + (max_y - min_y) across all blocks
    connected to that net. Only site-level (x, y) coordinates are used;
    BEL/sub-block positions are NOT considered, matching the convention
    in the FEM placer framework (see HPWLCalculator in hpwl.py).

    Args:
        coords: {block_name: (x, y)} — site-level coordinates only.
        nets: {net_name: [block_name, ...]} from the netlist file.

    Returns:
        dict with:
            - net_hpwl: {net_name: hpwl_value}
            - net_details: {net_name: {min_x, max_x, min_y, max_y,
                                       width, height, num_pins, missing_blocks}}
            - total_hpwl: float
            - avg_hpwl: float
            - num_nets: int
    """
    net_hpwl = {}
    net_details = {}
    total = 0.0

    for net_name, block_names in nets.items():
        xs, ys = [], []
        missing = 0
        for bname in block_names:
            if bname in coords:
                x, y = coords[bname]
                xs.append(x)
                ys.append(y)
            else:
                missing += 1

        if len(xs) < 2:
            continue

        min_x, max_x = min(xs), max(xs)
        min_y, max_y = min(ys), max(ys)
        hpwl = (max_x - min_x) + (max_y - min_y)

        net_hpwl[net_name] = hpwl
        net_details[net_name] = {
            'min_x': min_x,
            'max_x': max_x,
            'min_y': min_y,
            'max_y': max_y,
            'width': max_x - min_x,
            'height': max_y - min_y,
            'num_pins': len(xs),
            'missing_blocks': missing,
        }
        total += hpwl

    num_nets = len(net_hpwl)
    avg_hpwl = total / num_nets if num_nets > 0 else 0.0

    return {
        'net_hpwl': net_hpwl,
        'net_details': net_details,
        'total_hpwl': total,
        'avg_hpwl': avg_hpwl,
        'num_nets': num_nets,
    }


def print_hpwl_report(result: dict, circuit_name: str, place_file: str):
    """Print a formatted HPWL analysis report."""
    print("=" * 70)
    print(f"  VPR Placement HPWL Analysis Report")
    print(f"  Circuit : {circuit_name}")
    print(f"  Place   : {place_file}")
    print("=" * 70)
    print(f"  Total HPWL        : {result['total_hpwl']:>12.2f}")
    print(f"  Average HPWL      : {result['avg_hpwl']:>12.2f}")
    print(f"  Number of nets    : {result['num_nets']:>12d}")
    print("-" * 70)
    print(f"  Top 10 nets by HPWL:")
    print(f"  {'Net Name':<30} {'HPWL':>8} {'Pins':>5}")
    print(f"  {'-'*30} {'-'*8} {'-'*5}")
    sorted_nets = sorted(result['net_hpwl'].items(), key=lambda x: -x[1])
    for net_name, hpwl in sorted_nets[:10]:
        detail = result['net_details'][net_name]
        print(f"  {net_name:<30} {hpwl:>8.0f} {detail['num_pins']:>5d}")
    print("=" * 70)


def main():
    parser = argparse.ArgumentParser(
        description='Analyze FPGA placement file and compute HPWL at site level.'
    )
    parser.add_argument(
        'circuit',
        help='Circuit name (e.g., c2670, s1488). The script looks for '
             '<circuit>.place/.pl and <circuit>.net in the place_dir.'
    )
    parser.add_argument(
        '--place_dir',
        default='.',
        help='Directory containing placement and .net files (default: current dir).'
    )
    parser.add_argument(
        '--place_file',
        default=None,
        help='Explicit path to placement file (overrides circuit+place_dir).'
    )
    parser.add_argument(
        '--net_file',
        default=None,
        help='Explicit path to .net file (overrides circuit+place_dir).'
    )
    parser.add_argument(
        '--format',
        default='auto',
        choices=['auto', 'vpr', 'bookshelf'],
        help='Placement file format: "vpr" (VPR .place), '
             '"bookshelf" (ISPD Bookshelf .pl), '
             'or "auto" (detect from file extension/content).'
    )
    parser.add_argument(
        '--verbose', '-v',
        action='store_true',
        help='Print all nets (not just top 10).'
    )
    args = parser.parse_args()

    # Resolve file paths
    if args.place_file:
        place_path = args.place_file
    else:
        # Try .place first, then .pl
        place_path = os.path.join(args.place_dir, f'{args.circuit}.place')
        if not os.path.isfile(place_path):
            pl_path = os.path.join(args.place_dir, f'{args.circuit}.pl')
            if os.path.isfile(pl_path):
                place_path = pl_path

    if args.net_file:
        net_path = args.net_file
    else:
        # Try .net first, then .nets
        net_path = os.path.join(args.place_dir, f'{args.circuit}.net')
        if not os.path.isfile(net_path):
            nets_path = os.path.join(args.place_dir, f'{args.circuit}.nets')
            if os.path.isfile(nets_path):
                net_path = nets_path

    # Check files exist
    if not os.path.isfile(place_path):
        print(f"ERROR: Placement file not found: {place_path}")
        return 1

    # Detect / resolve format
    fmt = args.format
    if fmt == 'auto':
        fmt = detect_format(place_path)

    print(f"Placement file : {place_path}")
    print(f"Format         : {fmt}")

    # Parse placement file — only site-level (x, y) coordinates are extracted
    if fmt == 'bookshelf':
        coords = parse_place_file_bookshelf(place_path)
    else:
        coords = parse_place_file_vpr(place_path)
    print(f"  Found {len(coords)} blocks/instances with site-level coordinates.")
    print(f"  (BEL/sub-block positions are ignored — HPWL is site-level only)")

    if not os.path.isfile(net_path):
        print(f"WARNING: .net file not found: {net_path}")
        print("Cannot compute HPWL without netlist connectivity.")
        return 1

    print(f"Netlist file   : {net_path}")
    nets = parse_netlist(net_path, fmt=fmt if fmt != 'auto' else None)
    print(f"  Found {len(nets)} nets.")

    # Compute HPWL
    result = compute_hpwl(coords, nets)

    # Report
    print_hpwl_report(result, args.circuit, place_path)

    if args.verbose:
        print("\nAll nets:")
        print(f"  {'Net Name':<30} {'HPWL':>8} {'Pins':>5} {'Bbox':>16}")
        print(f"  {'-'*30} {'-'*8} {'-'*5} {'-'*16}")
        sorted_all = sorted(result['net_hpwl'].items(), key=lambda x: -x[1])
        for net_name, hpwl in sorted_all:
            detail = result['net_details'][net_name]
            bbox_str = f"({detail['min_x']},{detail['min_y']})-({detail['max_x']},{detail['max_y']})"
            print(f"  {net_name:<30} {hpwl:>8.0f} {detail['num_pins']:>5d} {bbox_str:>16}")

    return 0


if __name__ == '__main__':
    exit(main())
